/* Generated by Cython 3.1.0a1 */

#ifndef __PYX_HAVE__server
#define __PYX_HAVE__server

#include "Python.h"

#ifndef __PYX_HAVE_API__server

#ifdef CYTHON_EXTERN_C
    #undef __PYX_EXTERN_C
    #define __PYX_EXTERN_C CYTHON_EXTERN_C
#elif defined(__PYX_EXTERN_C)
    #ifdef _MSC_VER
    #pragma message ("Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.")
    #else
    #warning Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.
    #endif
#else
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C int add(int, int);
__PYX_EXTERN_C int subtract(int, int);

#endif /* !__PYX_HAVE_API__server */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

/* WARNING: Use PyImport_AppendInittab("server", PyInit_server) instead of calling PyInit_server directly from Python 3.5 */
PyMODINIT_FUNC PyInit_server(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"server\", PyInit_server) instead of calling PyInit_server directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"server\", PyInit_server) instead of calling PyInit_server directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"server\", PyInit_server) instead of calling PyInit_server directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit_server_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit_server() __PYX_WARN_IF_PyInit_server_INIT_CALLED(PyInit_server())
#endif

#endif /* !__PYX_HAVE__server */
